// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejfrwvfsppsusjkdjrtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZnJ3dmZzcHBzdXNqa2RqcnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Nzc2ODUsImV4cCI6MjA2OTQ1MzY4NX0.an0P2y1zmPepdG_mSx_Ia1fudIm9jC2cug2xwB6Rtto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});